from shop.models import Item, Purchase

item_1 = Item.objects.create(name='Lamborghini', price=180000)
item_2 = Item.objects.create(name='Ferrari', price=150000)
item_3 = Item.objects.create(name='Ваз', price=5000)
item_4 = Item.objects.create(name='Mercedes', price=150000)
item_5 = Item.objects.create(name='BMW', price=18000)
item_6 = Item.objects.create(name='Lada', price=1800)
item_7 = Item.objects.create(name='Honda', price=5800)
item_8 = Item.objects.create(name='Toyota', price=55800)
item_9 = Item.objects.create(name='Mazda', price=42850)
item_10 = Item.objects.create(name='Nissan', price=25000)

item_3.purch.create(name='Nurlan', age=33)
item_10.purch.create(name='Myrza', age=25)
item_3.purch.create(name='Daulet', age=16)
item_8.purch.create(name='Iman', age=19)
item_7.purch.create(name='Mirsaid', age=23)
item_6.purch.create(name='Bek', age=22)
item_5.purch.create(name='Aitegin', age=25)
item_1.purch.create(name='Takhir', age=18)
item_2.purch.create(name='Rustam', age=20)
item_9.purch.create(name='Uluk', age=33)
item_4.purch.create(name='Edil', age=21)
item_2.purch.create(name='Arina', age=19)
item_5.purch.create(name='Begayim', age=26)
item_9.purch.create(name='Ormon', age=20)
item_4.purch.create(name='Angelina', age=20)
item_6.purch.create(name='Anton', age=23)
item_8.purch.create(name='Anastasia', age=33)
item_1.purch.create(name='Nurlan', age=33)
item_7.purch.create(name='Jordan', age=28)
item_4.purch.create(name='Mike', age=48)


